### ISSUE TITLE
Deploy new version to mvn

### ISSUE THREAD

**Issue by mgobec** [smartcat-labs/cassandra-migration-tool-java#20]

**Comment by nbozic** [comment]
We need to do couple of things here:

1. Sync JCenter migration tool to our BinTray repo (2.1.9.0. already exists because it is synced from maven central)
2. Connect Jcenter and our Maven cetral
3. Release 2.1.9.1. to our BinTray which will sync to Jcenter repo and later to Maven Central

**Comment by nbozic** [comment]
@mgobec @nivancevic All is configured, we have now project on our bintray, it is synced with JCenter and you have Maven Central sync tab which can be triggered manually with one of our accounts (nexus accounts)
