### ISSUE TITLE
Cleanup pom.xml

### ISSUE THREAD

**Issue by slamdev** [smartcat-labs/cassandra-migration-tool-java#24]
Seems that dependencies below are not used and can be safely removed:
- `com.google.guava:guava`
- `org.fusesource:sigar`

And `org.mockito:mockito-all` can be set to `<scope>test</scope>` since it is used only for tests

**Comment by mgobec** [comment]
@slamdev Done in #25. Release coming shortly.

**Comment by slamdev** [comment]
@mgobec thanks! 
btw: the snapshot version works perfectly with cassandra 3. Good job!
