### ISSUE TITLE
Unable to get 3.1.0 version

### ISSUE THREAD

**Issue by slamdev** [smartcat-labs/cassandra-migration-tool-java#28]
Seems that the latest released version is absence in both [maven central](http://mvnrepository.com/artifact/io.smartcat/cassandra-migration-tool) and [jcenter](https://bintray.com/smartcat-labs/maven/cassandra-migration-tool-java) repos.

**Comment by nbozic-zz** [comment]
We will add it tomorrow, thanks for info.

**Comment by nbozic-zz** [comment]
We have released new version to jcenter and maven central. Note that sync with maven central can take some time but on jcenter it is up.
