### ISSUE TITLE
Allow Consistency Quorum as part of MigrationEngine.migrate instead of only Consistency All

### ISSUE THREAD

**Issue by miguelcasanova** [smartcat-labs/cassandra-migration-tool-java#30]
Currently, we run the migration tool as part of the deployment process, and we deploy multiples times a day in about tens of nodes, so it would reduce the chance of a failure and still keep the strong consistency.

Migrator.withSession( session).usingQuorumConsistency().build();
and by default keep All.

Happy to do the work and submit the PR, but let me know what do you think first?
Thanks

**Comment by mgobec** [comment]
Hi Miguel,

Only place where we enforce consistency is in the CassandraVersioner when we either retrieve or update schema version. If you think about it, it makes sense to have strong consistency for schema version operations.
I think that for development process we could extract this to be configurable but on a production system you don't want to do any schema or data migrations if you have operational issues with your cluster.

What are the issues for not meeting the consistency level when running deployment multiple times a day?

**Comment by miguelcasanova** [comment]
Hi Matija,
So far just got a timeout issue during a deployment in one of the nodes (3 responses were required but only 2 replica responded), but you are absolutely right. 
Thanks
