### ISSUE TITLE
Request for information: why is consistency level set to ALL?

### ISSUE THREAD

**Issue by dalvizu** [smartcat-labs/cassandra-migration-tool-java#36]
e.g:
https://github.com/smartcat-labs/cassandra-migration-tool-java/blob/790a0580770fba707d31e0c767d380707c6da3fc/src/main/java/io/smartcat/migration/CassandraVersioner.java#L62

```
    public int getCurrentVersion(final MigrationType type) {
        final Statement select = QueryBuilder.select().all().from(SCHEMA_VERSION_CF)
                .where(QueryBuilder.eq(TYPE, type.name())).limit(1).setConsistencyLevel(ConsistencyLevel.ALL);
        final ResultSet result = session.execute(select);

```

Is there a reason that this consistency level is set to ALL?

**Comment by mgobec** [comment]
Technically it can be a QUORUM as we just need to make sure we are getting consistent response but if ALL fails you have downed nodes in the cluster and you don't want to change the schema at that point anyways. Do you see a use case where this should be configurable?

**Comment by dalvizu** [comment]
Hi Matija -- we're seeing an error in our deployment where the coordinator node does not receive a response from one node in a six node cluster. Our cluster crosses two AWS regions (us-west-2 and us-east-2) and we are using the default `read_request_timeout_in_ms` value of 5000ms (https://docs.datastax.com/en/cassandra/3.0/cassandra/configuration/configCassandra_yaml.html). So nodes are not down necessarily but we cannot run an ALL consistency level query in our cluster.

We've fixed this by doubling the `read_request_timeout_in_ms` to 10000ms. 

Would you be open to a merge request moving these queries to LOCAL_QUORUM? I believe that schema agreement, at the least, is adequately checked:

https://github.com/smartcat-labs/cassandra-migration-tool-java/blob/790a0580770fba707d31e0c767d380707c6da3fc/src/main/java/io/smartcat/migration/Migration.java#L81
